-- Add store-scoped logical keys without rewriting the live legacy primary keys.
-- A surrogate-key cutover is intentionally deferred until a real cross-store
-- collision is observed and can be migrated in a dedicated maintenance window.

ALTER TABLE senhas_publicas
  ADD COLUMN IF NOT EXISTS cloud_row_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  ADD COLUMN IF NOT EXISTS installation_id TEXT,
  ADD COLUMN IF NOT EXISTS preferencial BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE IF EXISTS feedbacks
  DROP CONSTRAINT IF EXISTS feedbacks_ticket_id_fkey;
CREATE UNIQUE INDEX IF NOT EXISTS uq_senhas_publicas_store_local_id
  ON senhas_publicas (tenant_id, store_id, id);

ALTER TABLE toledo_produtos_publicos
  ADD COLUMN IF NOT EXISTS cloud_row_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  ADD COLUMN IF NOT EXISTS installation_id TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS uq_toledo_produtos_publicos_store_plu
  ON toledo_produtos_publicos (tenant_id, store_id, plu);

ALTER TABLE configuracoes_publicas
  ADD COLUMN IF NOT EXISTS cloud_row_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  ADD COLUMN IF NOT EXISTS installation_id TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS uq_configuracoes_publicas_store_chave
  ON configuracoes_publicas (tenant_id, store_id, chave);

ALTER TABLE comandos_operador
  ALTER COLUMN comando DROP NOT NULL,
  ALTER COLUMN status SET DEFAULT 'pending';
UPDATE comandos_operador SET status = 'pending' WHERE status = 'pendente';

ALTER TABLE IF EXISTS feedbacks
  ADD COLUMN IF NOT EXISTS tenant_id UUID,
  ADD COLUMN IF NOT EXISTS store_id UUID;
ALTER TABLE IF EXISTS feedbacks
  ALTER COLUMN ticket_id TYPE BIGINT USING ticket_id::BIGINT;
CREATE INDEX IF NOT EXISTS idx_feedbacks_store_created_at
  ON feedbacks (tenant_id, store_id, created_at DESC);
ALTER TABLE IF EXISTS feedbacks
  DROP CONSTRAINT IF EXISTS feedbacks_store_ticket_fkey;
ALTER TABLE IF EXISTS feedbacks
  ADD CONSTRAINT feedbacks_store_ticket_fkey
  FOREIGN KEY (tenant_id, store_id, ticket_id)
  REFERENCES senhas_publicas (tenant_id, store_id, id)
  ON DELETE CASCADE;
